/* AUTOR:MIGUEL VALDEZ
EXAMEN II PARCIAL - PROGRAMACION DE NEGOCIOS
08 DEE JULIO DEL 2019
*/
USE tempdb
GO
IF EXISTS(SELECT * FROM sys.databases WHERE name='ERP')
BEGIN
	DROP DATABASE ERP
END
GO

CREATE DATABASE ERP
GO

USE ERP
GO

CREATE SCHEMA Usuarios
GO

CREATE TABLE Usuarios.Usuario
(
Nombre NVARCHAR(50) NOT NULL,
Apellido NVARCHAR(50) NOT NULL,
NombreUsuario NVARCHAR(50) NOT NULL,
Contraseña	NVARCHAR(50) NOT NULL,
Correo NVARCHAR(50) NOT NULL,
FechaCreacion DATETIME2 DEFAULT GETDATE() NOT NULL,
UltimaConexion DATETIME2 DEFAULT GETDATE() NOT NULL,
Estado NVARCHAR(8) DEFAULT 'ACTIVO'
)
GO
